### PR TITLE
Prevent repetition xD

### PR DESCRIPTION
**Pull request by 2ec0b4**
On macOS, i had to add `-i ''` xD

### CODE REVIEW

**Comment by karolmajta** [comment]
Doesn't work on linux. You're right, we need to be extra careful to make it work cross-platform xD

**Comment by 2ec0b4** [comment]
Just update the pull request xD

**Comment by karolmajta** [comment]
This was resolved here https://github.com/karolmajta/git-xd-hook/pull/2 xD
Thanks for your contribution xD

**Comment by 2ec0b4** [comment]
I preferred my version, more KISS xD

**Pull request closed without merging**
